name: Windows MSVC Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest  # Windows Server 2022

    steps:
    - uses: actions/checkout@v3  # Клонирование репозитория

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1  # Активация MSVC (Visual Studio)

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    # Опционально: запуск тестов
    - name: Run tests
      run: |
        cd build
        ctest -C Release --output-on-failure
